# Generated by Django 4.1.5 on 2023-01-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('video_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('publish_time', models.DateTimeField()),
                ('channel_tile', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField()),
            ],
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['-publish_time', 'title', 'description'], name='searchAPI_y_publish_7e8391_idx'),
        ),
    ]
