# Generated by Django 4.1.5 on 2023-01-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='youtubevideo',
            name='searchAPI_y_publish_7e8391_idx',
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['-publish_time'], name='searchAPI_y_publish_1741d6_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['title'], name='searchAPI_y_title_83c3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['description'], name='searchAPI_y_descrip_234096_idx'),
        ),
    ]
